### ISSUE TITLE
where is the “resnet_flow.py” file?

### ISSUE THREAD

**Issue by jingge326** [mbilos/stribor#1]
Dear Marin,

Thanks very much for sharing this work! In the “Version 0.2.0”, I can’t find the file “resnet_flow.py” under “stribor.net”. Would you like to give me some hints on how to find the ResNetFlow model? Or maybe add some introduction on how to use the new version of stribor to do neural-flow experiments. Thanks!

**Comment by mbilos** [comment]
You can use the following to define a single transformation:
```py
f = st.ContinuousIResNet(dim, hidden_dims, time_net=st.net.TimeTanh(dim))
```
It's likely that this will again change in the future but you can just install the older version to avoid errors.
